webapp/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webportal.views.home', name='home'),
    url(r'^$', 'webapp.views.index'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

webapp/forms.py
from django import forms
from models import Contributor , Reviewer, Class
from models import Subject ,Comment, Language, Contact
from django.contrib.auth.models import User
from webapp.models import Contributor
from django.contrib import messages


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'placeholder': 'Your name*.'}),
        help_text="Enter your name.", required=True)
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class':'form-control',
                                  'placeholder': 'Enter valid email*.'}),
        help_text="Enter Email.", required=True)
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class':'form-control',
                                     'placeholder': 'Please write your message*.',
                                     'rows': 4}),
        help_text="Please write your message.", required=True)
    
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']#, 'captcha']


class UserForm(forms.ModelForm):
    """
    Fields are:

    USERNAME: He is the user who sign in.

    FIRST_NAME: This field tells the First name of the user. 

    LAST_NAME: This field tells the Last name of the user. 

    EMAIL: Email field tells the mail id of the user who sign in.

    PASSWORD: This tells the user to set his own password.
    """
    username = forms.CharField(label='Username',
    	widget = forms.TextInput(attrs={'class': 'form-control',
	    'placeholder': 'Username  to login*.'}), 
		help_text="", required =True,
		    error_messages={'required':'Username is required.'})
    first_name = forms.CharField(
        widget= forms.TextInput(
            attrs={'class': 'form-control',
                'placeholder': 'First name*.'}),
           				 help_text="", required=True,
       						 error_messages={'required':'First name is required.'})
    last_name = forms.CharField(
        widget= forms.TextInput(
            attrs={'class': 'form-control',
                'placeholder': 'Last name*.'}),
       		    help_text="", required=True,
        	        error_messages={'required':'Last name is required.'})

    email = forms.CharField(
       	widget= forms.TextInput(
            attrs={'class': 'form-control',
                'placeholder': 'Valid email*.'}),
                    help_text="", required=True,
        	        error_messages={'required':'Valid Email address is required.'})
    password = forms.CharField(
       	widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                'placeholder': 'Password*.'}),
       	            help_text="", required=True,
      		        error_messages={'required':'Password is missing.'})

    class Meta:
   	model =  User
        fields = ('username', 'first_name', 'last_name', 'email', 'password',)


class ContributorForm(forms.ModelForm):	
    """
    Fields are:

    CONTACT: This is the contact number of the user. It must be an integer.

    VALIDATION_DOCS: The Valid certificate of the user stating his educational qualifications. 

    PICTURE: The profile picture of the contributor. may be jpg or jpeg or png or bmp.
    """
    contact  = forms.CharField(
       	widget= forms.TextInput(
           attrs={'class': 'form-control', 
               'placeholder': 'Contribter contact number.'}),
                   help_text="", required=False,
       		       error_messages={'required':'Last name is required.'})

    validation_docs = forms.FileField(
       	label = 'Validation file.',
    	    widget = forms.FileInput(),
                #help_text = 'Upload validation file.',
        	    required=False)

    picture = forms.ImageField(label='Profile picture',
        widget = forms.FileInput(
            attrs={'placeholder': 'Contributor picture.'}),
                required=False)
    class Meta:
        model =  Contributor
        fields = ('picture', 'contact', 'validation_docs')

    def clean_validtion_docs_file(self):
        """Limit doc_file upload size."""
        if self.cleaned_data['validation_docs']:
            validation_docs= self.cleaned_data['validation_docs']
            return validation_docs
	else:
            raise forms.ValidationError("Not a valid file!")


class ReviewerForm(forms.ModelForm):	
    """
    Fields are:

    PICTURE: The profile picture of the Reviewer. may be jpg or jpeg or png or bmp.

    CONTACT: This is the contact number of the user. It must be an integer.
    """
    error_css_class = 'error'
    required_css_class = 'required'
    picture = forms.ImageField(label='Profile picture',
        widget = forms.FileInput(
            attrs={'placeholder': 'Reviewer picture.'}),required=False)
    contact  = forms.CharField(
       	widget= forms.TextInput(
            attrs={'class': 'form-control','placeholder': 'Reviewer contact number.'}),
        	help_text="", required=False,
       		    error_messages={'required':'Last name is required.'})
    class Meta:
        model =  Reviewer
     	fields = ('picture', 'contact')


class ContributorUploadForm(forms.ModelForm):
    """
    Fields are:

    CLASS_NUMBER: This will be class number like first, second .. eight .. tenth.

    NAME: This field is the name of the subject,the contributor is specialized in.

    TOPIC: The subject of the topic the contibutor is going to contribute.

    PDF: The contributor has to upload the files.This field describes that the uploaded file must be a pdf file. 

    VIDEO: The contributor has to upload the files.This field describes that the uploaded file must be a video. May be mp4.

    ANIMATION: The contributor has to upload the files.This field describes that the uploaded file must be an animation file. This may be gif.

    SUMMARY: This is the summary given by the contributor about the specified topic of the specified subject including when to use and how to use.
    """
    language = forms.ModelChoiceField(
	label='Language',
	cache_choices=True,
	widget=None,
	queryset=Language.objects.all(),
	empty_label=None,
	help_text="",required=True,
        error_messages={'required':'Language is required'})
    class_number = forms.ModelChoiceField(
	label='Class',
	cache_choices=True,
	widget=None,
	queryset=Class.objects.all(),
	empty_label=None,
	help_text="",required=True,
        error_messages={'required':'Class is required'})	
    name = forms.CharField(
        widget= forms.TextInput(
        attrs={'class': 'form-control','placeholder': 'Subject name*.'}),
        help_text="", required=True,
       	error_messages={'required':'Subject name is required.'})			
    topic = forms.CharField(
        widget= forms.TextInput(
        attrs={'class': 'form-control','placeholder': 'Subject topic*.'}),
        help_text="", required=True,
        error_messages={'required':'Subject topic is required.'})
    pdf = forms.FileField(
        label = 'pdf file.',
        widget = forms.FileInput(),
        help_text = 'Upload pdf file.',required=False)
    video = forms.FileField(
        label = 'video file.',
	help_text = 'Upload video file.',required=False)
    animation = forms.FileField(
        label = 'animations file.',
        widget = forms.FileInput(),
        help_text = 'Upload animations file.',required=False)
    summary = forms.CharField(label='Summary',
	widget= forms.Textarea(
        attrs={'class': 'form-control','placeholder': 'Summary for the uploaded documents.'}),
	help_text="", required=True,
	error_messages={'required':'Summary is required.'})  
     	
    class Meta:
        model = Subject
        fields = ['language','class_number', 'name','topic', 'pdf', 'video', 'animation', 'summary']
    
    def clean_pdf(self):
        """Upload a valid ."""
	print "Hey welcome"
        if self.cleaned_data['pdf']:
            pdf= self.cleaned_data['pdf']
	    print pdf.content_type.split('/')[1]
	    if pdf.content_type.split('/')[1] == "pdf":
	    	if pdf._size/(1024*1024) <= 20: # < 20MB
                	return pdf
		
            	else:
			raise forms.ValidationError("Filesize should be less than 20MB.")
            else:
	    	raise forms.ValidationError("Not a valid file, Please upload a pdf file!")

    def clean_video(self):
      	"""Limit doc_file upload size."""
	print "yoyo"
        if self.cleaned_data['video']:
	    print "hey"
            video= self.cleaned_data['video']
            if video.content_type.split('/')[1] in ("mp4", "x-matroska", "x-msvideo", "x-flv"):
        	if video._size/(1024*1024) <= 200: # < 100MB 
                	return video
		
            	else:
                	raise forms.ValidationError("Filesize should be less than 200MB.")
	    else:
	    	raise forms.ValidationError("Not a valid file, Please Upload a mp4, mkv, avi or flv file")

    def clean_animation(self):
        """Limit doc_file upload size."""
        if self.cleaned_data['animation']:
            animation= self.cleaned_data['animation']
	    if animation.content_type.split('/')[1] == "x-shockwave-flash":
        	if animation._size/(1024*1024) <= 10: # < 10MB
                	return animation
		
            	else:
                	raise forms.ValidationError("Filesize should be less than 10MB.")
	    else:
	    	raise forms.ValidationError("Not a valid file, Please Upload .swf file!")


class CommentForm(forms.ModelForm):
    """
    Field  is: 
  
    COMMENT: This field describes the comment form which takes maximum length of 1000 characters. The comment is made by the reviewer.
    """
    comment = forms.CharField(
        widget= forms.Textarea(
        attrs={'class': 'form-control','rows': '3'}),
        help_text="", required=False,
	)

    class Meta:
        model = Comment
        fields = ['comment']	

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Aakash School Education{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
     <link href="{% static 'css/freelancer.css' %}" rel="stylesheet" type="text/css">
     <link href="{% static 'css/mycss.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet" type="text/css">

    <!-- Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- IE8 support for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>
<body id="page-top" class="index">


    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Aakash School Education</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="/about/">About</a>
                    </li>


                    <li class="page-scroll">
                        <a href="/language/">Content</a>
                    </li>


	             {% if user.is_authenticated %}
		     
		    <!--  {% if contributor %} -->
		    <!-- <li class="page-scroll"> -->
		    <!--   <a href="/contributor/upload/">upload</a> -->
		    <!-- </li> -->
		    <!-- {% elif user in reviewer %} -->
		    <!--   <li class="page-scroll"> -->
		    <!-- 	<a href="/reviewer/profile/">review</li> -->
		    <!--   {% endif %} -->

            
		    <li class="dropdown">
		     <a href="" class="dropdown-toggle"
		         data-toggle="dropdown">{{user.username}}<b class="caret"></b></a>
		    <ul class="dropdown-menu">
		    		{% if user.contributor %}
				<li><a href="/contributor/profile/">Profile</a></li>
				{% elif user.reviewer %}
				<li><a href="/reviewer/profile/">Profile</a></li>
                {% else %}
                <li><a href="/admin">Django Admin</a></li>
				{% endif %}
			        <li><a href="/logout/">Logout</a></li>
             		</ul>
		    </li>
		    {% else %}
            <li class="dropdown">
		       <a href="#" class="dropdown-toggle"
		          data-toggle="dropdown">Register<b class="caret"></b></a>
		       <ul class="dropdown-menu">
			 <li><a href="/reviewer/signup/">Reviewer</a></li>
			 <li><a href="/contributor/signup/">Contributor</a></li>
		       </ul>
		     </li>
 		    <li><a href="/login/">Login</a></li>

            {% endif %}
		    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block content %}
    {% endblock content %}


    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Location</h3>
                        <p>IIT Bombay,
                            <br>Powai,Maharashtra<br>
                            PIN- 400076</p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li><a href="https://www.facebook.com/" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li><a href="https://plus.google.com/" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li><a href="https://www.twitter.com/" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li><a href="https://in.linkedin.com/" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li><a href="https://dribbble.com/" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Website</h3>
                        <p>This Website is a intended to supply appropriate study material to school students.<a href="http://startbootstrap.com"></a>.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; 2014 - Your Name
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'js/classie.js' %}"></script>
    <script src="{% static 'js/cbpAnimatedHeader.js' %}"></script>
    <script src="{% static 'js/freelancer.js' %}"></script>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
- Contact us
{% endblock title %}

{% block content %}
<div class="container  footer_padding" style="padding-top:1.5cm;">
  <div class="page-header">
      <h1><i class="fa fa-phone"></i> Contact us |<small> We’re here to help with any
      questions or comments.</small>
      </h1>
  </div>
  <div class="row">
    <div class="col-lg-6 well">
      <form role="form" id="contact-us" method="post"
	    enctype="multipart/form-data">
	{% csrf_token %}
	<!-- {{contactform.as_p}} -->
	<!-- Success/Error messages -->
	{% if messages %}
	{% for message in messages %}
	{% if message.tags == "success" %}
	<p class="text-info" align="center"><strong>{{ message }}</strong></p>
	{% else %}
	<p class="text-danger" align="center"><strong>{{ message }}</strong></p>
	{% endif %}
	{% endfor %}
	{% endif %} 
	<!-- Success/Error messages ends here -->
        <div class="form-group">
	  <!-- {{contactform.name.errors}} -->
          <label for="id_name">Name</label>
	  {{contactform.name}}
        </div>

        <div class="form-group">
	  <!-- {{contactform.email.errors}} -->
          <label for="id_email">Email</label>
	  {{contactform.email}}
        </div>
        
        <div class="form-group">
	  <!-- {{contactform.message.errors}} -->
          <label for="id_message">Message</label>
	  {{contactform.message}}
        </div>

	<input type="submit" name="submit" class="btn btn-primary"
	       value="Submit" />

	<input type="reset" name="submit" class="btn btn-info"
	       value="Reset" />
      </form>
    </div>
    
    
    <div class="col-lg-6" align="center">
      <br><br><br><br>
      <span class="glyphicon glyphicon-home"></span>
      <address>
        <strong>Aakash School Education</strong><br>
        Second Floor, Old CSE Building,<br>
        Indian Institute of Technology Bombay<br>
	Powai, Mumbai 400076,<br>
	Maharashtra, India.<br>
      </address>

      <address>
	<span class="glyphicon glyphicon-phone-alt"></span>
        (+91) (022) 25764708
      </address>    

      <address>
	<span class="glyphicon glyphicon-envelope"></span>
        <a href="mailto:aakashtechsupport@cse.iitb.ac.in">aakashtechsupport@cse.iitb.ac.in</a>
      </address>      
    </div>
    
  </div> <!-- row -->
</div><!-- /.container -->
{% endblock content %}


templates/content.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container footer_padding" align="center" style="padding-top:8%">
</div>
<div class="container footer_padding" align="center" style="padding-top 2.5cm">
<div class="col-md-12 well">
    <table class="table-responsive">
    <h1>{{Subject.name}}</h1>
    {% if uploads %}
    </div>
</div>

<style type="text/css">
	#tfnewsearch{
		float:right;
		padding:20px;
	}
	.tftextinput4{
		margin: 0;
		padding: 6px 15px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:16px;
		color:#666;
		border:1px solid #0076a3; border-right:1px solid #0076a3;
		border-top-left-radius: 5px 5px;
		border-bottom-left-radius: 5px 5px;
		border-top-right-radius: 5px 5px;
		border-bottom-right-radius: 5px 5px;	
	}
</style>

		<form id="tfnewsearch" method="get" action="/search/{{lang}}">
			<p><label for="id_q">Search:</label>
		        <input type="text" id="id_q" class="tftextinput4" name="q" size="21" maxlength="120" placeholder="Enter Subject or Topic">
			<button type="submit" class="add-on"><i class="fa fa-search"></i></button>

		</form>
		<div class="tfclear"></div>
	
<div class="table-responsive">
    <table class="table table-hover" id="uploads">
        <tr class="success">
           <td><strong>Class</strong></td>
           <td><strong>Subject</strong></td>
           <td><strong>Topic</strong></td>
           <td><strong>Summary</strong></td>
           <td><strong>PDF</strong></td>
           <td><strong>Video</strong></td>
           <td><strong>animation</strong></td>
                    
        </tr>
        {% for i in uploads %}
           <tr class="active">
           <td><strong>{{i.class_number}}</strong></a>
           </p>
          </td>
                 
           <td><strong>{{i.name}}</strong></a>
           </p>
           </td>
                    {% if user.is_authenticated %}
                    {% if user.contributor %}
                    <td><a href="/contributor/profile/{{i.class_number}}/{{i.name}}/{{i.topic}}/{{i.id}}"><strong>{{i.topic}}</strong></a>
                    </td>
                    {% elif user.reviewer %}
                    <td><a href="/reviewer/profile/{{i.class_number}}/{{i.name}}/{{i.topic}}/{{i.id}}"><strong>{{i.topic}}</strong></a>
                    </td>
                    {% endif %}
                    
                    {% else %}
                    <td><strong>{{i.topic}}</strong></a>
                    </td>
                    {% endif %}
                    
                    <td>
                      {{i.summary|safe|linebreaks}}
                    </td>
                    
                    <td>
                    {% if i.pdf %}
                      <a href="/media/{{i.pdf}}"><i class="fa fa-file-pdf-o fa-2x"></i></a>
                        {% else %}
                    {% endif %} </td><td>
                    {% if i.video %}
                    <a href="/media/{{i.video}}"><i class="fa fa-file-video-o fa-2x"></i></a>
                    {% else %}
                    {% endif %} </td><td>
                    {% if i.animation %}
                    <a href="/media/animation/{{i.animation}}"><i class="fa fa-file-image-o fa-2x"></i></a>
                    {% else %}
                    {% endif %} 
                    </td>         
                  </tr>
                {% endfor %}
		</table>
	<ul class="pagination" id="unordered-code-list"></ul> 
				{% else %}
  				<p>Nothing to display.</p>
  				{% endif %}

	</div>
<script src="{% static 'js/paging.js' %}"></script>
<script type="text/javascript">
 var pager = new Pager('uploads', 6, 'unordered-code-list');
</script>
</div>
{% endblock content %}

templates/contributor.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container" style= "padding-top: 5%; padding-bottom:5%">
<div class="row">
  	<div class="col-md-12">
   		 <div class="row">
      				<div class="col-md-8" style= " background-color:#d5dce1; margin-top:8%">
                                
				<h3>contribution in class</h3>
				{% for i in uploads %}
				<table class="table table-hover">
			        <td><a href="/contributor/profile/{{i}}">Class {{i}}</a></td><hr>	
				{% endfor %}

				</table>
            			</div><div class="col-md-1"></div>
      				<div class="col-md-3" style= " background-color:#cad3d9; margin-top:8%"><br/>
				<strong>Welcome {{contributor.user.username}}</strong><br><br>
				{% if contributor.picture %}
                                <img src="/media/{{contributor.picture}}" width=100px height=100px align="center">
				{% else %}
				<img src = "{% static 'img/default.png' %}" width=100px height=100px align="center">
				{% endif %}
				<br><br>
                                <a href= "/contributor/upload/">Upload more </a><br><br>

				<a href="/contributor/profile/edit/">
    				<button id='Edit-Profile-button' class="btn btn-primary" type='submit' ><span>Edit Profile</span></button></a><br/><br/>
  				<a href="/user/password/change">
   			        <button id='Password-reset-button'  type='submit' class="btn btn-primary"><span>Change Password</span></button></a><br><br>
  
              </div>
				
            </div>
    			</div>
  </div>
   </div>
{% endblock content %}

templates/contributor_subject.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container" style= "padding-top: 5%; padding-bottom:5%">
<div class="row">
  	<div class="col-md-12">
   		 <div class="row">
      				<div class="col-md-8" style= " background-color:#d5dce1; margin-top:8%">
				{% if uploads %}
                                <h4>Subjects corresponding to class {{class_num}}</h4>
				<table class="table table-hover" id="uploads">	
				{% for i in uploads %}
				<table class="table table-hover">    				
			        <td><h5><a href="/contributor/profile/{{class_num}}/{{i}}">{{i}}</a><hr>
				</h5></td>
				{% endfor %}
				</table>

				<ul class="pagination" id="unordered-code-list"></ul> 
  			</div><div class="col-md-1"></div>
      				<div class="col-md-3" style= " background-color:#cad3d9; margin-top:8%"><br/>
				<strong>Welcome {{contributor.user.username}}</strong><br><br>
                                {% if contributer.picture %}
                                <img src="/media/{{contributor.picture}}" width=100px height=100px align="center">
			{% else %}
				<img src = "{% static 'img/default.png' %}" width=100px height=100px align="center">
				{% endif %}

				<br><br>
                                <a href= "/contributor/upload/">Upload more </a><br><br>
				<a href="/contributor/profile/edit/">
    				<button id='Edit-Profile-button' class="btn btn-primary" type='submit' ><span>Edit Profile</span></button></a><br/><br/>
  				<a href="/user/password/change">
   			        <button id='Password-reset-button'  type='submit' class="btn btn-primary"><span>Change Password</span></button></a><br><br>
  
                          	</div>
				
				
                            </div>
				<ul class="pagination" id="unordered-code-list"></ul> 
				{% else %}
  				<p>Nothing to display.</p>
  				{% endif %}

    			</div>
  </div>
   </div>

<script src="{% static 'js/paging.js' %}"></script>
<script type="text/javascript">
var pager = new Pager('uploads', 5, 'unordered-code-list');
</script>
{% endblock content %}
                 

templates/language_select.html
{% extends 'base.html' %}
{% block content %}
<div class="container" style="padding-top:10% ; padding-bottom:10%">
<div class="col-md-12" style= " background-color:#d5dce1; margin-top:8%">
<center><h3>PLEASE SELECT YOUR LANGUAGE</h3></center>
			
<div style="width:230px; margin:0 auto;">
		                <div ul class="dropdown" align="center"> 
		       <a href="#" class="dropdown-toggle" 
		          data-toggle="dropdown" align="center">Language<b class="caret"></b></a>
		       <ul class="dropdown-menu">
			 {% for i in languages %}
			 <li><a href="/content/{{i}}/">{{i}}</a></li>
			 {% endfor %}
		       </ul>
		     </ul>
</div>
</div>
<br>
<br><br>
</div>
	</table>
            			</div>


{% endblock content %}

templates/reviewer_comment.html
{% extends 'base.html' %}
{% block content %} 
{% load static %}
<div class="container" style= "padding-top: 5%; padding-bottom:5%">
    <div class="row">
  	<div class="col-md-12">
            <div class="row">
   	        <div class="col-md-8" style= " background-color:#d5dce1; margin-top:8%">
	   	    <h4>comments corresponding to class {{class_num}}:{{sub}}-{{topics}}</h4><br>
                        <div>
			    <form id="comment_form" method="post"
                		enctype="multipart/form-data">
            		    {% csrf_token %}
				<!-- <p><label for="id_comment">Comment:</label>
    				<input id="id_comment" type="text" name="comment" /></p> -->
				{{comment_form.as_p}}
				<p align="right"><input type="submit" name="submit" class="btn btn-primary" value="Comment" align="right"  /></p>
			    </form>
			    <br>
			</div>	
			    {% for i in comment %}
			        <p><div class="row">
					<div class="col-md-11" style="margin-left:10px;background-color:#ffffff ">
					<b><em>{{i.comment}}</em></b>
					</div>
				   </div>
				   <div class="row">
				       <div class="col-md-5 col-md-offset-7">
				           <em>by: {{i.user}}<br>  on {{i.submit_date}}</em>
					</div>
			   	    </div>
			    {% endfor %}
		</div>
      		<div class="col-md-1">
		</div>
      		    <div class="col-md-3" style= "margin-top:8%;background-color:#d5dce1"><br>
			<strong>Welcome {{reviewer.user.username}}</strong><br><br>
                            {% if reviewer.picture %}
                                <img src="/media/{{reviewer.picture}}" width=100px height=100px align="center">
			    {% else %}
				<img src = "{% static 'img/default.png' %}" width=100px height=100px align="center">
				{% endif %}
				<br><br>
				<a href= "/reviewer/past/approvals/">Past Approvals </a><br><br>
      				<a href="/reviewer/profile/edit/">
    				    <button id='Edit-Profile-button' class="btn btn-primary" type='submit' >
					<span>Edit Profile</span></button></a><br/><br/>
  				<a href="/user/password/change">
   			            <button id='Password-reset-button'  type='submit' class="btn btn-primary">
					<span>Change Password</span></button></a><br><br>
  
                    </div>
				
				
             </div>
    	</div>
    </div>
</div>
{% endblock content %}